<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="JDLMetamodel" nsURI="src/metamodels/PIM/JDLMetamodel.ecore" nsPrefix="mde">
  <eClassifiers xsi:type="ecore:EClass" name="Application">
    <eStructuralFeatures xsi:type="ecore:EReference" name="config" lowerBound="1"
        eType="#//Config" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entities" upperBound="-1"
        eType="#//Entity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="deployments" upperBound="-1"
        eType="#//Deployment" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Config">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="baseName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="applicationType" eType="#//ApplicationType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="servicePort" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="databaseType" eType="#//DatabaseType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Entity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fields" upperBound="-1"
        eType="#//Field" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="relationships" upperBound="-1"
        eType="#//Relationship" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ApplicationType">
    <eLiterals name="MICROSERVICE"/>
    <eLiterals name="GATEWAY" value="1"/>
    <eLiterals name="MONOLITH" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DatabaseType">
    <eLiterals name="SQL"/>
    <eLiterals name="MONGODB" value="1"/>
    <eLiterals name="CASSANDRA" value="2"/>
    <eLiterals name="COUCHBASE" value="3"/>
    <eLiterals name="NO" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Field">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isRequired" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isUnique" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="min" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="max" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Relationship">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiplicity" eType="#//Multiplicity"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fromName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="toName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fromColumn" lowerBound="1"
        eType="#//RelationshipColumn" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Multiplicity">
    <eLiterals name="ONE_TO_MANY" literal="ONE_TO_MANY"/>
    <eLiterals name="MANY_TO_ONE" value="1" literal="MANY_TO_ONE"/>
    <eLiterals name="ONE_TO_ONE" value="2" literal="ONE_TO_ONE"/>
    <eLiterals name="MANY_TO_MANY" value="3" literal="MANY_TO_MANY"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="RelationshipType">
    <eLiterals name="UNIDIRECTIONAL" literal="UNIDIRECTIONAL"/>
    <eLiterals name="BIDIRECTIONAL" value="1" literal="BIDIRECTIONAL"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RelationshipColumn">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isRequired" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entity" lowerBound="1"
        eType="#//Entity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JDLPIM">
    <eStructuralFeatures xsi:type="ecore:EReference" name="applications" upperBound="-1"
        eType="#//Application" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entities" upperBound="-1"
        eType="#//Entity" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="enums" upperBound="-1"
        eType="#//Enum" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Deployment">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deploymentType" eType="#//DeploymentType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="directoryPath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DeploymentType">
    <eLiterals name="DOCKER"/>
    <eLiterals name="KUBERNETES" value="1"/>
    <eLiterals name="OPENSHIFT" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnidirectionalRelationship" eSuperTypes="#//Relationship">
    <eStructuralFeatures xsi:type="ecore:EReference" name="toEntity" lowerBound="1"
        eType="#//Entity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BidirectionalRelationship" eSuperTypes="#//Relationship">
    <eStructuralFeatures xsi:type="ecore:EReference" name="toColumn" lowerBound="1"
        eType="#//RelationshipColumn" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Enum">
    <eStructuralFeatures xsi:type="ecore:EReference" name="literals" lowerBound="1"
        upperBound="-1" eType="#//Literal" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Literal">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
  </eClassifiers>
</ecore:EPackage>
